#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

function audit_subdomain() {
  domain=$1
  subdomain=$2
  dig_result=$(dig $subdomain.$domain | awk '/^'$subdomain'/,/^$/')
  record_type=$(echo "$dig_result" | awk '/^'$subdomain'\./ { print $4 }')
  destination=$(echo "$dig_result" | awk '/^'$subdomain'\./ { print $5 }')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  audit_subdomain $domain www
  audit_subdomain $domain lb-01
  audit_subdomain $domain web-01
  audit_subdomain $domain web-02
else
  audit_subdomain $domain $subdomain
fi
