#!/usr/bin/env bash
# This script displays information about subdomains.

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "The subdomain $2 is a $line record and points to $3"
}

if [ "$#" == 1 ]; then
  domain=$1
  domain_information "$domain" "www" $(dig +short "www.$domain")
  domain_information "$domain" "lb-01" $(dig +short "lb-01.$domain")
  domain_information "$domain" "web-01" $(dig +short "web-01.$domain")
  domain_information "$domain" "web-02" $(dig +short "web-02.$domain")
elif [ "$#" == 2 ]; then
  domain=$1
  subdomain=$2
  domain_information "$domain" "$subdomain" $(dig +short "$subdomain.$domain")
fi
