#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*

cat << EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 54.152.246.245:80 check
    server 54.144.141.32:80 check

EOF

sudo service haproxy start
