#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
apt-get -y update

# Add Haproxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0

# Install Haproxy
apt-get -y install haproxy=2.0.\*

sudo bash -c 'cat <<EOF >/etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 157418-web-01 54.152.246.245:80 check
    server 157418-web-02 54.144.141.32:80 check
EOF'

sudo service haproxy enable
sudo service haproxy restart
