#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

sudo apt update
sudo apt install haproxy

cat << EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

frontend http_front
   bind *:80
   mode http
   default_backend http_back
backend http_back
   mode http
   balance roundrobin
   server 157418-web-01 54.152.246.245:80 check
   server 157418-web-02 54.144.141.32:80 check

EOF

sudo service haproxy start
