#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 80?
# configures nginx to run and listen to port 80

sudo mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
echo "Nginx is now listening on port 80."
