#!/usr/bin/env bash
# configure nginx to run and listen to port 80
sudo mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo servic nginx restart
