#!/usr/bin/env bash
# Changes Nginx config to run as nginx user and listens on port 8080
sudo service nginx stop
useradd -r nginx
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
