#!/usr/bin/env bash
# Changes Nginx config to run as nginx user and listens on port 8080
useradd -r nginx
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;\n\tlisten [::]:8080 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
